[package]
name = "mybinprj"
version = "0.1.0"
authors = ["My Name <my@email.addr>"]
edition = "2018"

[dependencies]
clap = "2"
directories = "1.0"
serde = { version = "1.0",  features = ["derive"] }
toml = "0.5"
